---
- hosts: all
  remote_user: root
  tasks:
    - name: Check sudo installed
      apt:
        name: sudo
        state: present

    - name: Check sudo without passwd
      copy:
        src: files/sudoers
        dest: /etc/sudoers
        owner: root
        group: root
        mode: 0440

    - name: Add user liquidpredator
      user:
        name: liquidpredator
        append: yes
        groups: sudo
        state: present

    - name: Add ssh keys for liquidpredator
      authorized_key:
        state: present
        user: liquidpredator
        key: https://github.com/liquidpredator.keys
