---
- hosts: web
  remote_user: liquidpredator
  become_method: sudo
  tasks:
    - name: Installing NGINX configuration
      template:
        src: liquidpredator.devops.srwx.net.conf.j2
        dest: /etc/nginx/sites-available/liquidpredator.devops.srwx.net
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: Enabling NGINX configuration
      file:
        src: /etc/nginx/sites-available/liquidpredator.devops.srwx.net
        path: /etc/nginx/sites-enabled/liquidpredator.devops.srwx.net
        state: link
      become: yes
      notify: NGINX reload

    - name: Installing Frontend application
      copy:
        src: front/
        dest: /srv/frontend/
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: Installing PHPAPI application
      copy:
        src: php/
        dest: /srv/phpapi/
        owner: root
        group: root
        mode: 0644
      become: yes

    - name: Installing GO application
      copy:
        src: go/
        dest: /srv/goapi/
        owner: root
        group: root
        mode: 0644
      become: yes
    
    - name: Installing GO application service
      copy:
        src: sysd/goapp.service
        dest: /lib/systemd/system/goapp.service
        owner: root
        group: root
        mode: 0744
      become: yes
      notify: Enable GO application

  handlers:
    - name: NGINX reload
      systemd:
        name: nginx
        state: reloaded
      become: yes

    - name: Enable GO application
      systemd:
        daemon_reload: yes
        name: goapp.service
        enabled: yes
        state: started
      become: yes
