---
- hosts: web
  remote_user: root

  vars:
    nginx_remove_default_vhost: true
    nginx_server_tokens: "off"

    php_webserver_daemon: "nginx"
    php_packages:
      - php-fpm
    php_install_recommends: false
    php_default_version_debian: "7.0"
    php_enable_php_fpm: true
    php_fpm_listen: "/run/php/php7.0-fpm.sock"

    certbot_create_if_missing: true
    certbot_admin_email: liquidpredator@gmail.com
    certbot_certs:
      - domains:
          - liquidpredator.devops.srwx.net
    certbot_create_standalone_stop_services:
      - nginx

    calc_domain_name: liquidpredator.devops.srwx.net
    calc_fpm_version: 7.0

  roles:
    - calc
    - calcdeploy
