---
- hosts: web
  remote_user: liquidpredator
  tasks:
    - name: Installing NGINX configuration
      copy: src=confs/liquidpredator.devops.srwx.net dest=/etc/nginx/sites-avalible/liquidpredator.devops.srwx.net owner=root group=root mode=0644
      file: src=/etc/nginx/sites-avalible/liquidpredator.devops.srwx.net path=/etc/nginx/sites-enabled/liquidpredator.devops.srwx.net state=link
      notify: NGINX reload

    - name: Installing Frontend application
      copy: src=front/ dest=/srv/frontend/ owner=root group=root mode=0644

    - name: Installing PHPAPI application
      copy: src=php/ dest=/srv/phpapi/ owner=root group=root mode=0644

    - name: Installing GO application
      copy: src=go/ dest=/srv/goapi owner=root group=root mode=0644
      copy: src=sysd/goapp.service dest=/lib/systemd/system/goapp.service owner=root group=root mode=0644
      notify: Enable GO application

  handlers:
    - name: NGINX reload
      systemd: name=nginx state=reloaded

    - name: Enable GO application
      systemd: daemon_reload=yes name=goapp enabled=yes state=started
