---
- hosts: backend
  remote_user: root

  include_vars:
    - backvars.yml

  vars:
    php_packages:
      - php-fpm
    php_install_recommends: false
    php_enable_php_fpm: true

    phpapi_repo: 
      - name: phpapi
      - repo: "https://github.com/liquidpredator/fevlake-calc-diff.git"
      - version: master

    goapi_repo:
      - name: goapi
      - repo: "https://github.com/liquidpredator/fevlake-calc-sum.git"
      - version: master

  roles:
    - geerlingguy.php
    - phpapi
    - goapi
