---
- hosts: backend
  remote_user: root

  #  vars_files:
  #    - backvars.yml

  vars:
    php_packages:
      - php-fpm
        #    php_install_recommends: false
    php_enable_php_fpm: true
    php_fpm_listen: 9090

    phpapi_name: phpapi
    phpapi_repo: "https://github.com/liquidpredator/fevlake-calc-diff.git"
    phpapi_version: master

    goapi_name: goapi
    goapi_repo: "https://github.com/liquidpredator/fevlake-calc-sum.git"
    goapi_version: master

  roles:
    - geerlingguy.php
    - phpapi
    - goapi
