---
- hosts: web
  remote_user: liquidpredator
  become_method: sudo
  tasks:
    - name: Add certbot repo & updating apt cache
      apt_repository:
        repo: ppa:certbot/certbot
        state: present
        update_cache: yes
      become: yes

    - name: Installing NGINX
      apt:
        name: nginx
        state: present
      become: yes

    - name: Installing php-fpm
      apt:
        name: php-fpm
        state: present
      become: yes
      notify: Enable php-fpm

    - name: Installing Certbot
      apt:
        name: python-certbot-nginx
        state: present
      become: yes

    - name: Get LE certificate
      raw: certbot --nginx certonly --domains {{ inventory_hostname }} --email liquidpredator@gmail.com --non-interactive --agree-tos
      become: yes

    - name: Removing default NGINX config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
      notify: Reload NGINX

  handlers:
    - name: Reload NGINX
      systemd:
        name: nginx
        enabled: yes
        state: reloaded
      become: yes

    - name: Enable php-fpm
      systemd:
        name: php-fpm
        enabled: yes
        state: started
      become: yes

