---

- name: Installing NGINX site
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ set_domain_name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: NGINX reload

- name: Enabling NGINX configuration
  file:
    src: /etc/nginx/sites-available/{{ set_domain_name }}.conf
    path: /etc/nginx/sites-enabled/{{ set_domain_name }}.conf
    state: link
  notify: NGINX reload
