---
- name: Check repo directory
  file:
    path: /var/repos
    state: directory

- name: Checkout from git
  git:
    repo: "{{ front_repo.repo }}"
    dest: "/var/repos/{{ front_repo.name }}"
    version: "{{ front_repo.version }}"
  register: gitcheckout
  tags: deploy

- name: Sync front if changes
  synchronize:
    src: "/var/repos/{{ front_repo.name }}"
    dest: "{{ front_webapps_dir }}"
    recursive: yes
    delete: yes
    rsync_opts:
      - "--exclude=.git"
  delegate_to: "{{ inventory_hostname }}"
  when: gitcheckout.changed
  tags: deploy
