---
- name: Check repo directory
  file:
    path: /var/repos
    state: directory

- name: Checking for golang instalation
  apt:
    name: golang-go
    state: present
  tags: deploy

- name: Checking for GO app directory
  file:
    path: "{{ goapi_webapps_dir }}/{{ goapi_name }}"
    state: directory
  tags: deploy

- name: Checkout from git
  git:
    repo: "{{ goapi_repo }}"
    dest: "/var/repos/{{ goapi_name }}"
    version: "{{ goapi_version }}"
  register: gitcheckout
  tags: deploy

- name: Copy service file
  copy:
    src: goapp.service
    dest: /etc/systemd/system/goapp.service
    owner: root
    group: root
    mode: 0644
  register: gosrv

- name: Reload daemons & enable GOapp
  systemd:
    daemon_reload: yes
    name: goapp.service
    enabled: yes
  when: gosrv.changed

- name: Building GO app
  shell: go build -o {{ goapi_webapps_dir }}/{{ goapi_name }}/main /var/repos/{{ goapi_name }}/*.go
  notify: restart GO app
  when: gitcheckout.changed
  tags: deploy
