---
- name: Check repo directory
  file:
    path: /var/repos
    state: directory

- name: Checkout from git
  git:
    repo: "{{ item.repo }}"
    dest: "/var/repos/{{ item.name}}"
    version: "{{ item.version }}"
  register: gitcheckout
  with_items:
    - "{{ calcdeploy_repos }}"
  tags: deploy

- name: Sync if changes
  synchronize:
    src: "/var/repos/{{ item.item.name }}"
    dest: "{{ calcdeploy_webapps_dir }}"
    recursive: yes
    delete: yes
    rsync_opts:
      - "--exclude=.git"
  delegate_to: "{{ inventory_hostname }}"
  when: item.changed
  register: sync
  with_items: "{{gitcheckout.results }}"
  tags: deploy

- name: Restart GO app
  systemd:
    name: goapp.service
    state: restarted
  when: 
    - item.changed
    - item.item.item.name == "goapi"
  with_items: "{{sync.results}}"
  tags: deploy
