---
- name: Check repo directory
  file:
    path: /var/repos
    state: directory

- name: Checkout from git
  git:
    repo: "{{ item.repo }}"
    dest: "/var/repos/{{ item.name}}"
    version: "{{ item.version }}"
  register: gitcheckout
  with_items:
    - "{{ calcdeploy_repos }}"
  tags: deploy

- name: Sync front and phpapi if changes
  synchronize:
    src: "/var/repos/{{ item.item.name }}"
    dest: "{{ calcdeploy_webapps_dir }}"
    recursive: yes
    delete: yes
    rsync_opts:
      - "--exclude=.git"
  delegate_to: "{{ inventory_hostname }}"
  when:
    - item.changed
    - (item.item.name == "front") or (item.item.name == "phpapi")
  register: sync
  with_items: "{{gitcheckout.results }}"
  tags: deploy

- name: Include building GO app if changes
  include_tasks: goapi.yml
  when: 
    - item.changed == True
    - item.item.name == "goapi"
  with_items: "{{ gitcheckout.results }}"
  tags: deploy
