---

- name: Installing NGINX site
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ calc_domain_name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: NGINX reload

- name: Enabling NGINX configuration
  file:
    src: /etc/nginx/sites-available/{{ calc_domain_name }}.conf
    path: /etc/nginx/sites-enabled/{{ calc_domain_name }}.conf
    state: link
  notify: NGINX reload

- name: Installing GO API service
  template:
    src: goapp.service
    dest: /etc/systemd/system/goapp.service
    owner: root
    group: root
    mode: 0644
  notify: reload daemons
